// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Partas.Solid.Primitives.Keyboard")>]
[<assembly: AssemblyProductAttribute("Partas.Solid.Primitives.Keyboard")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Partas.Solid.Primitives.Keyboard"
    let [<Literal>] AssemblyProduct = "Partas.Solid.Primitives.Keyboard"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
