[bump]
initial_tag = "0.2.0"
[git]
conventional_commits = true
filter_unconventional = false
filter_commits = false
topo_order = false
sort_commits = "newest"
[[git.commit_preprocessors]]
pattern = "\\((\\w+\\s)?#([0-9]+)\\)"
replace = ""

[[git.commit_parsers]]
message = "^\\[skip ci\\]"
skip = true
[[git.commit_parsers]]
group = "Added"
message = "^[a|A]dd"
[[git.commit_parsers]]
group = "Added"
message = "^[s|S]upport"
[[git.commit_parsers]]
group = "Removed"
message = "^[r|R]emove"
[[git.commit_parsers]]
group = "Added"
message = "^.*: add"
[[git.commit_parsers]]
group = "Added"
message = "^.*: support"
[[git.commit_parsers]]
group = "Removed"
message = "^.*: remove"
[[git.commit_parsers]]
group = "Removed"
message = "^.*: delete"
[[git.commit_parsers]]
group = "Fixed"
message = "^test"
[[git.commit_parsers]]
group = "Fixed"
message = "^fix"
[[git.commit_parsers]]
group = "Fixed"
message = "^.*: fix"
[[git.commit_parsers]]
group = "Changed"
message = "^.*"

[changelog]
header = "\n# Changelog\n\nAll notable changes to this project will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\n"
body = "{%- macro remote_url() -%}\r\n    https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\r\n{%- endmacro -%}\r\n\r\n{% if version -%}\r\n    ## [{{ version | trim_start_matches(pat=\"v\") | trim_end_matches(pat=\"-Partas.Solid.Primitives.ActiveElement\") }}] - { timestamp | date(format=\"%Y-%m-%d\") }\r\n{% else -%}\r\n    <h2>\r\n\r\n        [Unreleased]\r\n    \r\n    </h2>\r\n{% endif -%}\r\n\r\n{% for group, commits in commits | group_by(attribute=\"group\") %}\r\n    <h3>{{ group | upper_first }}</h3>\r\n    {%- for commit in commits %}\r\n        - {{ commit.message | split(pat=\"\n\") | first | upper_first | trim }} {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}\r\n            {% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) {%- endif -%}\r\n    {% endfor %}\r\n{% endfor %}\r\n\r\n{%- if github.contributors | filter(attribute=\"is_first_time\", value=true) | length != 0 %}\r\n  <h2>New Contributors</h2>\r\n{%- endif -%}\r\n\r\n{% for contributor in github.contributors | filter(attribute=\"is_first_time\", value=true) %}\r\n  * @{{ contributor.username }} made their first contribution\r\n    {%- if contributor.pr_number %} in [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) {%- endif %}\r\n{%- endfor %}\r\n"
footer = "\n{%- macro remote_url() -%}\n  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\n{%- endmacro -%}\n\n{% for release in releases -%}\n    {% if release.version -%}\n        {% if release.previous.version -%}\n            [{{ release.version | trim_start_matches(pat=\"v\") }}]: {{ self::remote_url() }}/compare/{{ release.previous.version }}..{{ release.version }}\n        {% endif -%}\n    {% else -%}\n        [unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}..HEAD\n    {% endif -%}\n{% endfor %}\n<!-- generated by git-cliff -->\n<!-- using Partas Fake.Tools.GitCliff -->\n"
trim = true
output = "RELEASE_NOTES.md"
[remote]
